name = "shared"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
lily = { path = "../.." }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
